server:
  port: 8087

spring:
  application:
    name: rating-service

  datasource:
    url: jdbc:mysql://localhost:3306/rating_db?createDatabaseIfNotExist=true
    username: root
    password: Srinurajee@1999
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: Rating Service
    description: Restaurant and delivery partner rating and review system
    version: 1.0.0
    port: 8087
    features:
      - Restaurant ratings and reviews
      - Delivery partner ratings
      - Average rating calculation
      - Review management

logging:
  level:
    com.fooddelivery.rating: DEBUG
