# EUREKA SERVER CONFIGURATION
# This file configures the Eureka Server settings

server:
  port: 8761  # Eureka Server runs on port 8761 (default)

spring:
  application:
    name: eureka-server  # Service name that appears in Eureka dashboard

eureka:
  client:
    # Since this is the Eureka Server itself, it should not register with itself
    register-with-eureka: false
    fetch-registry: false
    service-url:
      # This is where other services will connect to register themselves
      defaultZone: http://localhost:8761/eureka/
  
  server:
    # How long to wait before removing a service that hasn't sent a heartbeat
    eviction-interval-timer-in-ms: 10000
    # Disable self-preservation mode in development (keeps removing failed services)
    enable-self-preservation: false

# Logging configuration
logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
